export type BskEpubChapter = {
  index: number;
  order: number;
  title: string;
  href: string;
};

export const bskEpubMetadata = {
  "identifier": "urn:uuid:853167e3-7456-4159-95eb-53fb512d6468",
  "title": "Bir Şifacının Kanadı",
  "creator": "Figen Yavuz",
  "language": "tr",
  "publisher": "22 Yayınevi",
  "rights": "© 2026 Figen Yavuz"
} as const;

export const bskEpubChapters: BskEpubChapter[] = [
  {"index":0,"order":1,"title":"ARAYIŞIN YOLCULUĞU","href":"text/section-001.xhtml"},
  {"index":1,"order":2,"title":"MİNİK DETAYLARDAKİ BÜYÜK MUCİZELERİ GÖRMEK","href":"text/section-002.xhtml"},
  {"index":2,"order":3,"title":"GÖZÜN AÇIK GİTMESİN","href":"text/section-003.xhtml"},
  {"index":3,"order":4,"title":"TANRI ZAR ATMAMIŞ","href":"text/section-004.xhtml"},
  {"index":4,"order":5,"title":"BİR ÇİFT GÖZÜN DEĞDİĞİ ANDADIR BAZEN HUZUR","href":"text/section-005.xhtml"},
  {"index":5,"order":6,"title":"ÖĞRENDİM","href":"text/section-006.xhtml"},
  {"index":6,"order":7,"title":"SESSİZ YOLCULUK","href":"text/section-007.xhtml"},
  {"index":7,"order":8,"title":"ÇEMBERİN","href":"text/section-008.xhtml"},
  {"index":8,"order":9,"title":"HASSAS KİŞİLİK SENDROMU","href":"text/section-009.xhtml"},
  {"index":9,"order":10,"title":"ONDA OLAN PARÇAM","href":"text/section-010.xhtml"},
  {"index":10,"order":11,"title":"KENDİ HAKİKATİN AYNALARDA","href":"text/section-011.xhtml"},
  {"index":11,"order":12,"title":"KORKUNUN BÜYÜ ETKİSİ","href":"text/section-012.xhtml"},
  {"index":12,"order":13,"title":"İLAHÎ IŞIK RUHLAR","href":"text/section-013.xhtml"},
  {"index":13,"order":14,"title":"VEDALAR","href":"text/section-014.xhtml"},
  {"index":14,"order":15,"title":"YETİŞECEK YER YOK","href":"text/section-015.xhtml"},
  {"index":15,"order":16,"title":"AZAT ET","href":"text/section-016.xhtml"},
  {"index":16,"order":17,"title":"KAZANMAK DA VAR KAYBETMEK DE.","href":"text/section-017.xhtml"},
  {"index":17,"order":18,"title":"KARŞILAŞMALAR","href":"text/section-018.xhtml"},
  {"index":18,"order":19,"title":"SİZCE?","href":"text/section-019.xhtml"},
  {"index":19,"order":20,"title":"KENDİNDEN TANIRSIN BAZILARINI","href":"text/section-020.xhtml"},
  {"index":20,"order":21,"title":"EKSİK KALANLAR","href":"text/section-021.xhtml"},
  {"index":21,"order":22,"title":"NEFES VARSA UMUT OLUR","href":"text/section-022.xhtml"},
  {"index":22,"order":23,"title":"SEN SEV YETER","href":"text/section-023.xhtml"},
  {"index":23,"order":24,"title":"YOL","href":"text/section-024.xhtml"},
  {"index":24,"order":25,"title":"IŞIĞINI GÖRMEYENE GÜNEŞ OLMA","href":"text/section-025.xhtml"},
  {"index":25,"order":26,"title":"RUH SİMYACISI","href":"text/section-026.xhtml"},
  {"index":26,"order":27,"title":"İHTİYACIMIZ OLAN","href":"text/section-027.xhtml"},
  {"index":27,"order":28,"title":"AHENK","href":"text/section-028.xhtml"},
  {"index":28,"order":29,"title":"TANRI BEKLERKEN BULUNMAZMIŞ","href":"text/section-029.xhtml"},
  {"index":29,"order":30,"title":"ZATEN SAHİP OLMAK","href":"text/section-030.xhtml"},
  {"index":30,"order":31,"title":"SON EMİR","href":"text/section-031.xhtml"},
  {"index":31,"order":32,"title":"MARİFET İLTİFATA TABİDİR","href":"text/section-032.xhtml"},
  {"index":32,"order":33,"title":"İNSAN OLMAK","href":"text/section-033.xhtml"},
  {"index":33,"order":34,"title":"KAYBEDİP BULMAK","href":"text/section-034.xhtml"},
  {"index":34,"order":35,"title":"BU ALEMDE","href":"text/section-035.xhtml"},
  {"index":35,"order":36,"title":"HİÇBİR ŞEY GÖRÜNDÜĞÜ GİBİ DEĞİL","href":"text/section-036.xhtml"},
  {"index":36,"order":37,"title":"SESİ KISIK OLURMUŞ GÜZELLİĞİN","href":"text/section-037.xhtml"},
  {"index":37,"order":38,"title":"ASIL HİKÂYE VE SIRLAR","href":"text/section-038.xhtml"},
  {"index":38,"order":39,"title":"AYNA","href":"text/section-039.xhtml"},
  {"index":39,"order":40,"title":"RÜYALARIN SANCILI GEZİNTİSİ","href":"text/section-040.xhtml"},
  {"index":40,"order":41,"title":"BAZEN","href":"text/section-041.xhtml"},
  {"index":41,"order":42,"title":"HAYAT TEK KULLANIMLIK","href":"text/section-042.xhtml"},
  {"index":42,"order":43,"title":"KALBİ OKUYABİLMEK","href":"text/section-043.xhtml"},
  {"index":43,"order":44,"title":"MUCİZEYİZ","href":"text/section-044.xhtml"},
  {"index":44,"order":45,"title":"TEK HAKİKAT","href":"text/section-045.xhtml"},
  {"index":45,"order":46,"title":"HER ŞEY GEÇİYOR","href":"text/section-046.xhtml"},
  {"index":46,"order":47,"title":"YOL ALMAK","href":"text/section-047.xhtml"},
  {"index":47,"order":48,"title":"ORMANLAR","href":"text/section-048.xhtml"},
  {"index":48,"order":49,"title":"KİM OLDUĞUNU BİLMEK","href":"text/section-049.xhtml"},
  {"index":49,"order":50,"title":"DÖNÜN YOL YAKINKEN","href":"text/section-050.xhtml"},
  {"index":50,"order":51,"title":"DENGENİN HİKMETİ","href":"text/section-051.xhtml"},
  {"index":51,"order":52,"title":"YILDIZLARLA BULACAĞIN ŞİFA","href":"text/section-052.xhtml"},
  {"index":52,"order":53,"title":"VAR OLMAK","href":"text/section-053.xhtml"},
  {"index":53,"order":54,"title":"RÜYA","href":"text/section-054.xhtml"},
  {"index":54,"order":55,"title":"BAZILARI BAŞKADIR","href":"text/section-055.xhtml"},
  {"index":55,"order":56,"title":"TÜM HAKİKATİN ANLAŞILACAĞI AN","href":"text/section-056.xhtml"},
  {"index":56,"order":57,"title":"DEĞİŞİM İÇİN","href":"text/section-057.xhtml"},
  {"index":57,"order":58,"title":"BEDEN KAFTANIMIZ OLMASAYDI","href":"text/section-058.xhtml"},
  {"index":58,"order":59,"title":"BİR ŞEYİ DE BİLMEN GEREK","href":"text/section-059.xhtml"},
  {"index":59,"order":60,"title":"DEĞİŞİM","href":"text/section-060.xhtml"},
  {"index":60,"order":61,"title":"ERDEM YOLCULUĞU","href":"text/section-061.xhtml"},
  {"index":61,"order":62,"title":"MUTLULUK DEDİĞİN ŞEY","href":"text/section-062.xhtml"},
  {"index":62,"order":63,"title":"BİLSE SEVER MİYDİ BEŞER","href":"text/section-063.xhtml"},
  {"index":63,"order":64,"title":"EN BÜYÜK BULUŞ","href":"text/section-064.xhtml"},
  {"index":64,"order":65,"title":"ŞER VE HAYIR","href":"text/section-065.xhtml"},
  {"index":65,"order":66,"title":"SON EMİR","href":"text/section-066.xhtml"},
  {"index":66,"order":67,"title":"UNUTMAYI SEÇTİK UYANABİLİRDİK","href":"text/section-067.xhtml"},
  {"index":67,"order":68,"title":"GÖZLERİN KÜTÜPHANESİ","href":"text/section-068.xhtml"},
  {"index":68,"order":69,"title":"UMUT ŞARTTIR YAŞAMAK İÇİN","href":"text/section-069.xhtml"},
  {"index":69,"order":70,"title":"KODLARINIZ","href":"text/section-070.xhtml"},
  {"index":70,"order":71,"title":"BIRAKMAK","href":"text/section-071.xhtml"},
  {"index":71,"order":72,"title":"AŞK TÜKENDİ","href":"text/section-072.xhtml"},
  {"index":72,"order":73,"title":"TANIK OLMAK","href":"text/section-073.xhtml"},
  {"index":73,"order":74,"title":"SENİN KAPIN","href":"text/section-074.xhtml"},
  {"index":74,"order":75,"title":"BUL HİRAN’I","href":"text/section-075.xhtml"},
  {"index":75,"order":76,"title":"İNSANLAR KÖTÜ DOĞMAZLAR, SONRADAN OLURLAR","href":"text/section-076.xhtml"},
  {"index":76,"order":77,"title":"MASALARIM VAR BENİM","href":"text/section-077.xhtml"},
  {"index":77,"order":78,"title":"BİRİNİN FELAKETİ BİRİNİN MUCİZESİ","href":"text/section-078.xhtml"},
  {"index":78,"order":79,"title":"YOLUM SENDİN","href":"text/section-079.xhtml"},
  {"index":79,"order":80,"title":"İHTİŞAMLI BİR YARIN İÇİN","href":"text/section-080.xhtml"},
  {"index":80,"order":81,"title":"İNANDIĞIN KADAR VARSIN, İNANDIĞIN KADAR YAŞARSIN","href":"text/section-081.xhtml"},
  {"index":81,"order":82,"title":"YEMEĞİN PİŞTİĞİ YERDE MUTLAK KOKUSU SİNER ÜZERİNE","href":"text/section-082.xhtml"},
  {"index":82,"order":83,"title":"MAZİMDEN İSTİFA","href":"text/section-083.xhtml"},
  {"index":83,"order":84,"title":"AŞK","href":"text/section-084.xhtml"},
  {"index":84,"order":85,"title":"AŞKIN ARACILARI","href":"text/section-085.xhtml"}
];

export const bskEpubSource = {
  format: "EPUB3",
  packagePath: "EPUB/package.opf",
  navigationPath: "EPUB/nav.xhtml",
  chapterCount: bskEpubChapters.length,
  metadata: bskEpubMetadata,
  chapters: bskEpubChapters,
} as const;
